version: '3.8'

services:
  auth:
    build:
      context: . 
      dockerfile: ./apps/auth/Dockerfile 
    container_name: auth
    ports:
      - '3001:3000'
    environment:
      - NODE_ENV=production
      - DOMAIN=http://localhost
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_NAME=shortify
      - SECRET_KEY=secret
    depends_on:
      - postgres
    networks:
      - nx-network

  shortify:
    build:
      context: . 
      dockerfile: ./apps/shortify/Dockerfile
    container_name: shortify
    ports:
      - '3002:3000'
    environment:
      - NODE_ENV=production
      - DOMAIN=http://localhost
      - PORT=3000
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=admin
      - DB_PASSWORD=admin
      - DB_NAME=shortify
      - SECRET_KEY=secret
    depends_on:
      - postgres
    networks:
      - nx-network

  postgres:
    image: postgres:15 
    container_name: postgres
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: shortify
    ports:
      - '5432:5432' 
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - nx-network

networks:
  nx-network:
    driver: bridge


volumes:
  postgres-data: